name: Custom Deploy to GitHub Pages

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build for Github Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        # TODO: make this faster with https://github.com/jetli/wasm-pack-action/blob/master/README.md

      - name: Run Tests
        run: cargo test
      
      # # This will not run without wasm-bindgen-test as a dependence in Cargo.toml
      # - name: Run wasm-pack tests against headless browser of choice
      #   run: wasm-pack test --headless --chrome

      - name: build website
        run: wasm-pack build --target web --out-dir build --release

        ## store our files for the next step:
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./build
      
      
      
      
  deploy:
    name: Deploy to Github Pages
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist


      # - uses: actions/checkout@v2
      # # - name: Install dependencies
      # #   run: cargo ...
      # - name: build website
      #   run: wasp-pack build --target web
      # # Action to deploy to Github Pages branch:
      # - name: push to GithubPages branch
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     # Build output to push it to gh-pages branch
      #     publish_dir: ./build
      #     # The following lines assign commit authorship to the official
      #     # GH-Actions bot for deploys to `gh-pages` branch:
      #     # https://github.com/actions/checkout/issues/13#issuecomment-724415212
      #     # The GH actions bot is used by default if you didn't specify the two fields.
      #     # You can swap them out with your own user credentials.
      #     user_name: github-actions[bot]
      #     user_email: 41898282+github-actions[bot]@users.noreply.github.com
